version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: smart_code_analyzer/backend/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PROXYAPI_KEY=${PROXYAPI_KEY}
      - AI_MODEL=${AI_MODEL}
    command: uvicorn smart_code_analyzer.backend.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./smart_code_analyzer/frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./smart_code_analyzer/frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana_data:
