version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: smart_code_analyzer/backend/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/smart_code_analyzer
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: smart_code_analyzer/frontend/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smart_code_analyzer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
